adminUser:
  password: vault:leaderspice/adminUser:password
  username: admin
dashboardAuthID: vault:leaderspice:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:leaderspice:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:leaderspice/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:leaderspice/prow:hmacToken
